name: vscode-devcontainer-python-plugin
description: VSCode devcontainer configuration for Python apps.
display-name: vscode-devcontainer-python-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - python
  - docker
  - vscode
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
  - "Docker"
  - "Python"
types:
  - app
inputs:
  - label: Container name
    type: text
    name: container_name
    required: true
